name: release

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          persist-credentials: false

      - name: Install Rust dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf nsis lld llvm

      - name: Install node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Install Tauri dependencies
        run: |
          rustup target add x86_64-pc-windows-msvc
          cargo install cargo-xwin

      - name: Build webapp for docker and static webapp for tauri
        run: |
          mkdir -p 'web_static/app/(frontend)/'
          cp -rf 'web/app/(frontend)'/* 'web_static/app/(frontend)'
          mkdir -p web_static/public
          cp -rf web/public/* web_static/public
          cd yarn-web && yarn build && cd ..
          cd web_static && yarn install && cd ..

      - name: Swap to node 14 for semantic release compatibility
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Semantic Release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v3
        with:
          # You can specify specifying version range for the extra plugins if you prefer.
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/github
            @semantic-release/exec
            @google/semantic-release-replace-plugin@1.2.0
            @codedependant/semantic-release-docker
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_SEMANTIC_RELEASE }}
          DOCKER_REGISTRY_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
