name: release

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: windows-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    outputs:
      version: ${{ steps.semantic-release.outputs.new_release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          persist-credentials: false

      - name: Install node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Build webapp for docker and static webapp for tauri
        run: |
          yarn sync-app
          yarn build-web
          yarn build-static

      - name: Swap to node 14 for semantic release compatibility
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Semantic Release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v3
        with:
          # You can specify specifying version range for the extra plugins if you prefer.
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/github
            @semantic-release/exec
            @google/semantic-release-replace-plugin@1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_SEMANTIC_RELEASE }}

  publish-docker-image:
    runs-on: ubuntu-latest
    needs: build_and_release
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          persist-credentials: false

      - name: Install node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Build webapp for docker in NextJS standalone mode
        run: |
          cd web
          yarn install
          yarn build

      - name: login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push docker image
        run: |
          cd web
          docker build --tag cahaselerempact/empact:latest --tag cahaselerempact/empact:${{ needs.build_and_release.outputs.version }} .
          docker push
